- name: mysql setup
  hosts: all
  become: yes
  tasks:
    - name: install mysql community server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    - name: enable mysql service
      ansible.builtin.systemd:
         name: mysqld
         enabled: yes
         state: restarted
    - name: enable connection and set root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass Sriharsha@1