    - name: check nodejs installed or not
      ansible.builtin.shell: type npm
      ignore_errors: true
      register: npm
    - name: print nodejs status
      ansible.builtin.debug:
        msg: "{{ npm }}"
    - name: disable nodejs present version
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable nodejs current version 
      ansible.builtin.shell: dnf module enable nodejs:20 -y
  
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
      when: npm.rc != 0
    - name: add app user
      ansible.builtin.user:
        name: sri
    - name: copy backend service
      ansible.builtin.template:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: import role from common directory
      ansible.builtin.import_role:
        name: common
        tasks_from: app_prereq

    - name: download dependencies
      ansible.builtin.shell: npm install
      args: 
        chdir: /app
    - name: enable and restart backend service
      ansible.builtin.systemd_service:
        name: backend
        enabled: yes
        state: restarted
        daemon-reload: yes
    - name: install mysql setup
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: load schema
      ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'expense.backend.mysql_url', region='us-east-1' ) }} -uroot -p{{ lookup('amazon.aws.aws_ssm', 'expense.backend.mysql_password', region='us-east-1' ) }} < /app/schema/backend.sql