    - name: install nodejs repo
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: install nodejs
      ansible.builtin.dnf:
         name: nodejs
         state: installed

    - name: create user
      ansible.builtin.user:
         name: expense

    - name: import a role
      ansible.builtin.import_role:
         name: common
         tasks_from: app-prereq.yml

    - name: copy backend service
      ansible.builtin.copy:
         name: backend
         dest: /etc/systemd/system/backend.service
         enabled: yes
         state: restarted
         daemon-reload: yes

    - name: install mysql
      ansible.builtin.dnf:
         name: mysql
         state: installed

    - name: load schema
      ansible.builtin.shell: mysql -h mysql.sriharsha.shop -uroot -pSriharsha@1 < /app/schema/backend.sql