    - name: check nodejs installed or not
      ansible.builtin.shell: type npm
      ignore_errors: true
    - name: print nodejs status
      ansible.builtin.debug:
        msg: "nodejs status installed or not"
      register: npm_status
    - name: disable nodejs present version
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: enable nodejs current version 
      ansible.builtin.shell: dnf module enable nodejs:20 -y
  
    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
      when: rc != 0
    - name: add app user
      ansible.builtin.user:
        name: sri
    - name: copy backend service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: import role from common directory
      ansible.builtin.import_role:
        name: common
        tasks_from: app_prereq

    - name: download dependencies
      ansible.builtin.shell: npm install
      args: 
        chdir: /app
    - name: enable and restart backend service
      ansible.builtin.systemd_service:
        name: backend
        enabled: yes
        state: restarted
        daemon-reload: yes
    - name: install mysql setup
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: load schema
      ansible.builtin.shell: mysql -h mysql.sriharsha.shop -uroot -pSriharsha@1 < /app/schema/backend.sql