    - name: remove old html content and directory
      ansible.builtin.file:
        path: "{{ app_loc }}"
        state: absent
    - name: create a directory
      ansible.builtin.file:
        path: "{{ app_loc }}"
        state: directory 
    - name: download frontend code
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
        dest: "{{ app_loc }}"
        remote_src: yes