    - name: remove old html content and directory
      ansible.builtin.file:
        path: "{{ path_to_frontend }}"
        state: absent
    - name: create a directory
      ansible.builtin.file:
        path: "{{ path_to_frontend }}"
        state: directory 
    - name: download frontend code
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/"{{ component }}".zip
        dest: "{{ path_to_frontend }}"
        remote_src: yes