route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
  
receivers:
  - name: "email"
    email_configs:
      - to: harshasri618@gmail.com
        from: harshasri618@gmail.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: "{{ lookup('amazon.aws.aws_ssm', 'expense.prometheus.username', region='us-east-1') }}"
        auth_password: "{{ lookup('amazon.aws.aws_ssm', 'expense.prometheus.password', region='us-east-1') }}"
        require_tls: true
